[package]
name = "danbooru-tags-preprocess"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.91"
serde = { version = "1.0", features = ["derive"] }
glob = "0.3.1"
rayon = "1.6.1"
rustc-hash = "1.1.0"
serde-aux = "4.1.2"
indicatif = "0.17.3"
